name: Build STM32 MicroPython HEX (uLab)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi make python3 git

      - name: Clone MicroPython
        run: |
          git clone https://github.com/micropython/micropython.git
          cd micropython
          git checkout v1.23.0
          git submodule update --init --recursive

      - name: Clone uLab
        run: |
          git clone https://github.com/v923z/micropython-ulab.git ulab

      - name: Build firmware (FAST)
        run: |
          cd micropython/ports/stm32
          make BOARD=NUCLEO_F446RE \
          USER_C_MODULES=../../../ulab/code/micropython.cmake \
          CFLAGS_EXTRA="-DMODULE_ULAB_ENABLED=1" \
          -j4

      - name: Convert to HEX
        run: |
          arm-none-eabi-objcopy -O ihex \
          micropython/ports/stm32/build-NUCLEO_F446RE/firmware.elf \
          firmware.hex

      - name: Upload HEX
        uses: actions/upload-artifact@v4
        with:
          name: firmware-hex
          path: firmware.hex
